name: QA

on:
  push:
  pull_request:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    name: Static Analysis & Code Formatting

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run PHPStan
        run: make phpstan

      - name: Run Laravel Pint
        run: make csfix

      - name: Run Rector
        run: make rector

  php_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1,8.2, 8.3, 8.4]
        laravel: [^10.40, ^11.34, ^12.0]
        include:
          - laravel: ^10.40
            testbench: 8.*
          - laravel: ^11.34
            testbench: 9.*
          - laravel: ^12.0
            testbench: 10.*
    name: Tests PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      - name: Remove analysis dependencies
        run: |
          composer remove --dev --no-update larastan/larastan phpstan/phpstan shipmonk/composer-dependency-analyser driftingly/rector-laravel laravel/pint

      - name: Install dependencies
        run: |
          composer require --dev --no-update "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}"
          composer update --prefer-dist --no-interaction

      - name: Run tests
        run: make test
