name: QA

on:
  push:
  pull_request:

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    name: Static Analysis & Code Formatting

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      - name: Install dependencies
        run: |
          composer install --no-interaction
          cd tools
          composer install --no-interaction

      - name: Run PHPStan
        run: ./tools/vendor/bin/phpstan analyse --memory-limit=2G

      - name: Run Laravel Pint
        run: ./tools/vendor/bin/pint

      - name: Run Rector
        run: ./tools/vendor/bin/rector --dry-run
  php_tests:
    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [^10.40, ^11.34, ^12.0]
        os: [ubuntu-latest]
        include:
          - laravel: ^10.40
            testbench: 8.*
          - laravel: ^11.34
            testbench: 9.*
          - laravel: ^12.0
            testbench: 10.*
    name: ${{ matrix.php }} - ${{ matrix.laravel }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick

      - name: Install dependencies
        run: |
          composer require --dev "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}"
          composer install --no-interaction

      - name: Run csfix
        run: make csfix

      - name: Run phpstan
        run: make phpstan

      - name: Run rector
        run: make rector
